#!/usr/bin/env zsh

# DON'T USE NVM which slows down zsh
# --------------------------------

# Get profiling information(more detailed load time) by running: 'zprof'
zmodload zsh/zprof

# resolve the problem of compinit spending too much time
autoload -Uz compinit
for dump in ~/.zcompdump(N.mh+24); do
  compinit
done
compinit -C

# machine proxy settings
if uname -r | grep -qi microsoft; then
    # in wsl
    source ~/.config/zsh/proxy_settings_in_wsl.sh set
else
    # other unix-like systems
    source ~/.config/zsh/proxy_settings.sh
fi

source ~/.config/zsh/env.zsh                                # os-independent public env config
[[ -e ~/.profile ]] && emulate sh -c 'source ~/.profile'    # machine-dependent env config
source ~/.config/zsh/plugins.zsh                            # download plugins and config them
source ~/.config/zsh/themes.zsh
source ~/.config/zsh/fzf.zsh
source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/utils.zsh
